### ISSUE TITLE
一部のファイルでcross originエラー

### ISSUE THREAD

**Issue by wakufactory** [gsi-cyberjapan/gsimaps-vector-experiment#1]
自サイトにcloneして動かしてみた所、一部のファイルで、cross originのエラーが出ます。
response headerに access-control-allow-originが設定されていないようです。

対象ファイルは、
https://maps.gsi.go.jp/layers_txt/layers1.txt
等と
https://maps.gsi.go.jp/xyz/noto-jp/NotoSansCJKjp-Regular/
以下のファイル(Webフォント?)

で発生しています。ベクトルタイルデータそのものは大丈夫のようです。

**Comment by johofukyu** [comment]
国土地理院の地理院地図担当です。
地理院地図Vectorを早速ご利用いただきありがとうございます。

当該ファイルには「access-control-allow-origin: *」を設定しているところですが、
ユーザーのキャッシュが残っている場合、ご指摘のクロスオリジンエラーが発生することを、
当方の環境でも確認しました。

ユーザーキャッシュをクリアし、リロードしたところ、問題なく読み込みが行えることを確認しておりますので、まずはそちらをお試しいただければと思います。

引き続き、より詳細な調査を進めてまいります。

**Comment by wakufactory** [comment]
回答ありがとうございます。
なるほどキャッシュの問題でしたか・・・・ちょっとググったところ
https://codeday.me/jp/qa/20190315/373377.html
この辺りのCDNの問題のようにも見えます。
一番下にVaryヘッダを追加すれば良いというようなことが書いてあります。

**Comment by johofukyu** [comment]
ご指摘ありがとうございます。
いただいた情報を参考に、引き続き調査を進めてまいります。
よろしくお願いします。

**Comment by wakufactory** [comment]
こちらもその後出ていないようなので、一旦クローズします。
