### ISSUE TITLE
feature.id がタイルにセットされていない

### ISSUE THREAD

**Issue by miya0001** [gsi-cyberjapan/gsimaps-vector-experiment#10]
タイル内の各地物に id がセットされていないため、たとえば `map.setFeatureState()` などのメソッドが動作しないと思われます。

参考:

* [setFeatureState](https://docs.mapbox.com/mapbox-gl-js/api/#map#setfeaturestate) - `feature.id` が必須になっている。
* [Vector tile specification](https://docs.mapbox.com/vector-tiles/specification/#encoding-attributes) - わかりにくのですが、「Final vector tile」に `id` という要素があります。

必須では無いようですが、値があれば Mapbox GL JS のメソッドがすべて動作するのであったほうがいいかなと思いご報告しました。

**Comment by johofukyu** [comment]
地理院地図Vectorのご利用ありがとうございます。

タイルサイズ削減の観点から、現在各地物にidは付与しない仕様としております。
なお、今回いただいた情報は今後の参考とさせていただきます。

以上、よろしくお願いいたします。
