### ISSUE TITLE
`ftCode` に関する記載の誤り

### ISSUE THREAD

**Issue by miya0001** [gsi-cyberjapan/gsimaps-vector-experiment#11]
以下の資料「地物コード及び表示ズームレベル一覧」にて、道路で 2200 番台と 2400番台の `ftCode` を持つ地物がズームレベル 17 となっていますが、ズームレベル 16 でも存在しておりました。

https://maps.gsi.go.jp/help/pdf/vector/dataspec.pdf

### ズームレベル14-16のページでの記載内容

2200番台と2400番代に関する記述がない。

![](https://content.evernote.com/shard/s21/sh/dcd61e10-fd21-4559-a6cf-403f9a7c539a/2ea1ab3879af9603/deep/0/)

### ズームレベル17のページでの記載内容

![](https://www.evernote.com/l/ABV8LF0wZ85HoKqUFhBO_N5wl2ywMx7K9KEB/image.png)

これは、仕様書の方の記載漏れという理解で正しいでしょうか？ それともタイルの方の誤りでしょうか？（ズームレベル16から2200番台と2400番台のftCodeをもつ地物が削除される可能性がある？）

**Comment by johofukyu** [comment]
地理院地図Vectorをご利用いただきありがとうございます。

ズームレベル(ZL)17で表示される地物は、ZL16のタイルデータに格納されています。
（「データ仕様 ズームレベル17（地物）」の表の最も右側の列「各地物が格納されているタイルデータ」（※1）に、「ZL16」と記載しています。）
※1 列タイトルがPDF上 途切れておりましたので修正しました。

そのため、ZL16で表示される「道路」のftCodeは2700番台（※2）ですが、ZL16のタイルデータには、2200番台・2400番台の地物も格納されています。
※2 誤記がありましたので修正しました。

なお、地理院地図Vectorは試験公開中であり、各地物のftCodeや属性値については、今後検討していく中で見直される可能性もございますので、ご了承ください。

よろしくお願いいたします。

**Comment by miya0001** [comment]
ありがとうございます！
