### ISSUE TITLE
道路の接合と道路凡例のコードについて

### ISSUE THREAD

**Issue by gisenvision** [gsi-cyberjapan/gsimaps-vector-experiment#12]
提供実験の取り組み大変ご苦労様です。
さて、道路のデータについて2点ほど気づいた点があります。
私の処理の間違いかも知れませんし、元にした図面にも起因するのかとも思います。

１．レベル16の道路データ2701<=ftcode<= 2734のデータをいくつかの都道府県データについて眺めました。
ところどころ非常に微小ではあるものの、不連続があります。タイル間の不整合なのかそうでないのかわかりませんが、タイル間のものもあるようです。
QGIS3.10LTRでPBFを直接開いてから、もしくはGDALで変換処理してからの気づきですので、もしかするとソフトやプログラムの問題かもしれません。

２．地物等の属性一覧での定義表にないデータがある場合がある
地物等の属性一覧はhttps://maps.gsi.go.jp/help/pdf/vector/attribute.pdfを参考にしました。
共通属性と個別の属性などがありますが、この表にない数値が出現する場合があります。
例）PDF　5ページ目のmedSect
表では0、1、99となっていますが、2~18の間の数値が入っている場合がありました。

以上です。提供実験であることは重々承知しております。
今後もこのような素晴らしい取り組みを続けていただくためにも、微力ながら応援してまいります。

**Comment by johofukyu** [comment]
ベクトルタイルについてご指摘いただきありがとうございます。

１．に関して
ベクトルタイルを作成する過程で、今回ご指摘いただいたようにラインデータに非常に微小な不連続が生じている可能性がございます。
本件につきましては、対処するかどうかも含めて、今後の検討課題とさせていただきます。

２．に関して
medSect属性については、[お示しのPDF](https://maps.gsi.go.jp/help/pdf/vector/attribute.pdf)で、属性値「1」に対する説明を「有り」と記載しておりましたが、「幅1mの分離帯が存在する」が正しく、この度修正いたしました。
すなわち、属性値2～18についてはそれぞれの数値のm幅をもつ分離帯が存在するという意味でございます。

今後ともよろしくお願いいたします。

**Comment by gisenvision** [comment]
お忙しいところ、ご回答ありがとうございました。
２．のPDFのほうも確認しました。
１．については道路は点で接合するのでずれが目立つわけですが、本質的には道路だけの話でもないと思います。
一方で、このような問題をデータ的ではなくソフト的に乗り越える方法をお考えの方もいらしているかもしれません。
ともあれ、そのようなことに注意しつつ、使用してまいりたいと思います。

これにて、このissueについては閉じさせていただきます。
提供実験の取り組みへのご尽力感謝いたします。今後ともよろしくお願いします。
