### ISSUE TITLE
dataspec.pdf の機械可読形式データについて

### ISSUE THREAD

**Issue by frogcat** [gsi-cyberjapan/gsimaps-vector-experiment#13]
[dataspec.pdf / 地物コード及び表示ズームレベル一覧](https://maps.gsi.go.jp/help/pdf/vector/dataspec.pdf) を元に、たとえば本来存在しない `ftCode` を指定していないか、とか、本来「線」であるのに「点」のスタイルをアサインしていないか、といったようなスタイルのバリデーションのようなことをできないかと思っています。

そのためには、**dataspec.pdf** のデータを何らかの方法でプログラムにロードできるように加工しないといけないのですが、現状の PDF から機械可読なデータを作成するのはあまり簡単ではありません。（仮にPDF から表形式への機械的変換がうまくいったとしても、セルの連結解除がかなり扱いづらい点、またページごとにデータ項目が微妙に異なるので人力での正規化が必要な点が課題と思っています）

現状の **dataspec.pdf** に加えて、 **dataspec.csv** のような機械可読形式でデータ仕様を提供していただくことは可能でしょうか？

以下はズームレベル4〜7(地物)の一部とズームレベル4〜7(注記)の一部を手作業で表形式データとして作成してみたものですが、このような、ズームや地物注記によらずに共通化したレコードレイアウトの CSV 形式でデータが入手できると大変助かります。
https://gist.github.com/frogcat/058c57ce3aed169594c1cbb77b16e9db#file-dataspec-csv

**Comment by johofukyu** [comment]
ご要望いただき、ありがとうございます。

とりいそぎ、Excel版について公開いたしました。

https://maps.gsi.go.jp/help/pdf/vector/dataspec.xlsx

セルの連結やテーブル構造の統一に関するご提案については、今後の修正の際の参考とさせていただきます。

どうぞよろしくお願いします。

**Comment by frogcat** [comment]
早速ありがとうございます。PDF起点よりもだいぶ楽になりそうです。
