### ISSUE TITLE
ベクトルタイル用の `mokuroku.csv.gz` は提供されていないのでしょうか？

### ISSUE THREAD

**Issue by miya0001** [gsi-cyberjapan/gsimaps-vector-experiment#16]
質問で恐縮ですが、ベクトルタイル用の `mokuroku.csv.gz` に該当するものは提供されていないのでしょうか？
https://github.com/gsi-cyberjapan/mokuroku-spec

**Comment by johofukyu** [comment]
お示しいただいたページに記載のとおり、mokurokuは現在、ラスタタイルの標準地図、淡色地図、Englishのタイルのみ定期的に更新しております。

ベクトルタイルは現段階では実験的に提供しているものであり、タイルデータの随時更新は行っておらず、mokurokuも提供しておりません。

恐れ入りますがご了承ください。
よろしくお願いいたします。

**Comment by miya0001** [comment]
なるほど。ありがとうございます！
