### ISSUE TITLE
Source-layer symbolに含まれるgcpCodeFlagの意味について

### ISSUE THREAD

**Issue by gisenvision** [gsi-cyberjapan/gsimaps-vector-experiment#18]
Source-layer symbolのデータにgcpCodeFlagがあるのですが、これに対する説明の記載を見つけることができません。
電子基準点で付属金属標の位置＆高さのデータが1で、電子基準点の位置＆高さのデータがが0、その他はNullかと思うのですが、公式にはどのように0と1を定義されているのでしょうか？

https://maps.gsi.go.jp/help/pdf/vector/attribute.pdf
ではgcpCodeについても記載がないですし、https://fgd.gsi.go.jp/otherdata/spec/FGD_DLFileSpecV3.0.pdf
でもgcpCodeは基準点コードとありますが、gcpCodeFlagはありません。

データを見る限りだと以下の通りとなっています。
・ftcode＝7101の電子基準点で0か１（その他のftcodeではNull）
・gcpNameで（付）とあるものが1でそうでないものが0
・gcpNameで（付）とあるものとでそうでないものの位置は同じ、標高だけが違う、標高も5m程度（付）のほうが低い

以上です、検索してみてもgcpCodeFlagは2件しかヒットせず、データそのものがでてきてしまうので、お問い合わせさせていただいた次第です。よろしくおねがいします。

**Comment by johofukyu** [comment]
ご認識のとおり、提供実験中のベクトルタイルのズームレベル14から17において、gcpCodeFlagは電子基準点本点では0で、電子基準点の付属標では1としております。

お示しいただいた下記URLのPDFにつきましては、今後更新を検討いたします。
https://maps.gsi.go.jp/help/pdf/vector/attribute.pdf

よろしくお願いいたします。

**Comment by gisenvision** [comment]
担当者様
お忙しいところ、ご回答頂きまして、まことにありがとうございました。
