### ISSUE TITLE
高DPI環境での画像出力について

### ISSUE THREAD

**Issue by pickoba** [gsi-cyberjapan/gsimaps-vector-experiment#19]
MacのRetinaディスプレイのような高DPI環境で「画像として保存」を使用すると、地図上で指定した領域と画像として出力される領域が異なるものになってしまうようです（下図参照）。なお、これは「表示されている範囲全体」でも「範囲を固定」でも発生します。おそらく `devicePixelRatio` を考慮した切り出しになっていないのではないかと思います。

<img width="500px" alt="map" src="https://user-images.githubusercontent.com/48815688/223909595-d800e9cc-2391-4b94-b96a-65ee4ed13a12.png">
<img width="500px" alt="exported" src="https://user-images.githubusercontent.com/48815688/223909628-bdd6946b-e7e5-47d7-ba51-fa6d6b777759.png">

**Comment by johofukyu** [comment]
ご指摘いただきありがとうございます。

本日、修正を反映いたしました。
どうぞよろしくお願いいたします。

**Comment by pickoba** [comment]
正しく修正されていることを確認しました。素早いご対応ありがとうございます。
