### ISSUE TITLE
style.json が Style Specification に従っていない

### ISSUE THREAD

**Issue by frogcat** [gsi-cyberjapan/gsimaps-vector-experiment#2]
style.json について以下の説明があり、リンク先として <https://docs.mapbox.com/mapbox-gl-js/style-spec/> が指定されています。

> 地図のデザインを規定しているファイル。Style Specificationに従って記述されています。

Style Specification では少なくともルートオブジェクトのプロパティとして `version`  `sources`  `layers` が必須とされているのですが、 <https://maps.gsi.go.jp/vector/data/std.json> を始めとした各 style.json ファイルには `version`  `sources`  `layers` といったキーワードは含まれておらず、とくに Style Specification に準拠していないように思われます。

説明の誤りでしょうか？（実際はなんらかの独自仕様に従っている？）

**Comment by johofukyu** [comment]
国土地理院の地理院地図担当です。

style.jsonは、Style Specificationをベースとしておりますが、若干の拡張を施しています。
説明に誤りがあり申し訳ありません。

なお、拡張を施した理由は、建物をハッチで塗りつぶしたり、地物の複雑な上下関係を表したりするためには、Style Specificationそのままでは機能が不足していたからです。

**Comment by frogcat** [comment]
回答ありがとうございます＆状況理解できました。
以下で修正も確認できましたので本件クローズさせていただきます。
https://github.com/gsi-cyberjapan/gsimaps-vector-experiment/commit/1645d27d3090d7935b3a910d6a2daff05dc950c5
