### ISSUE TITLE
style.jsonでのレイヤーのfilterの決定基準について

### ISSUE THREAD

**Issue by rtr-dnd** [gsi-cyberjapan/gsimaps-vector-experiment#20]
こんにちは。鉄道や道路など属性を多く持つ地物について、公開されているstyle.jsonのレイヤーのfilterがどのように決定されているか公開されていますでしょうか。

こちらのdataspecを見ると、例えば鉄道はすべて単一のレイヤーに入っています：
https://maps.gsi.go.jp/help/pdf/vector/dataspec.pdf
style.jsonでは、rtCodeなど以下に記載されている属性値に応じてそれをフィルターしたものが各レイヤーとして分割されているという認識です：
https://maps.gsi.go.jp/help/pdf/vector/attribute.pdf

しかし、例えば[blank.json](https://github.com/gsi-cyberjapan/gsimaps-vector-experiment/blob/master/data/blank.json)において、「市区町村道・その他」においては「通常部（有料）」というtollSectで絞り込まれたレイヤーが存在する一方、「県道」においてはそのようなレイヤーが存在しません。
各style.jsonにおいて、具体的にどのような基準でレイヤーを分割しているかの仕様などがもし公開されていれば大変助かるのですが、いかがでしょうか。

**Comment by johofukyu** [comment]
地理院地図Vectorをご利用いただきありがとうございます。
 
ベクトルタイルデータにつきましては、元データとなるベクトルデータの一部の属性を継承する形でデータを作成しています。
元データにつきましては、厳密には同一ではありませんが、以下の国土地理院の数値地図（国土基本情報）、数値地図（国土基本情報20万）に近いデータですので、こちらの仕様が参考になるかと思います。
https://www.gsi.go.jp/kibanjoho/kibanjoho40027.html
https://www.gsi.go.jp/kibanjoho/kibanjoho40082.html
 
一方で、各styleJSONにおける描画定義につきましては、お問い合わせのようなレイヤ分割基準に関わる仕様はご用意しておりません。
なお、std.jsonやpale.jsonはそれぞれ地理院タイルの標準地図、淡色地図を模したスタイル定義となっております。

**Comment by rtr-dnd** [comment]
ありがとうございます。承知しました。クローズします。
