### ISSUE TITLE
data/std.json 高速道路番号のtext-fieldが"nRno"になっている

### ISSUE THREAD

**Issue by ohmusso** [gsi-cyberjapan/gsimaps-vector-experiment#23]
<https://github.com/gsi-cyberjapan/gsimaps-vector-experiment/blob/7bc33da1b80f888dafa159703373b4cc921ecd97/data/std.json>

高速道路番号のアイコン内の文字を描画する場合、text-fieldは"uRno"が正しいと思ったのですが、"nRno"となっている箇所がありました。間違っていないでしょうか？
![スクリーンショット 2024-07-16 220835](https://github.com/user-attachments/assets/ca31371d-2221-4c3c-ac8e-16c0cba56594)

※試験公開していただいている<https://maps.gsi.go.jp/vector/>は正しく描画されていそうです

**Comment by johofukyu** [comment]
地理院地図Vectorをご利用いただきありがとうございます。
 
text-fieldにつきましては、地物ごとに決められているのではなく、地物とそのズームレベルに応じて決められております。
そのため、お示しいただいた高速道路番号のtext-fieldに"nRNo"と"uRNo"が存在します。
ズームレベル8～10では"nRNo"、ズームレベル11～13では"uRNo"が付けられております。
（ご参考）gsi-cyberjapan＞gsimaps-vector-experiment＞README＞属性等の仕様詳細「地物コード及び表示ズームレベル一覧」
https://maps.gsi.go.jp/help/pdf/vector/dataspec.pdf

以上、よろしくお願いいたします。

**Comment by ohmusso** [comment]
説明していただいてありがとうございます。理解できました。
