### ISSUE TITLE
要望: 座標をクリップボードにコピーしたい

### ISSUE THREAD

**Issue by nek7u** [gsi-cyberjapan/gsimaps-vector-experiment#24]
Windows デスクトップ パソコンで利用しています。

【要望】地図上の地点を右クリックして、コンテキスト メニューから座標をクリップボードにコピーできるようにしてほしい。
フォーマットはGoogle マップのように、**緯度(Latitude),経度(Longitude)**。
（第1希望）`34.4577,136.7233` (`,`の前後にスペースなし)
（第2希望）`34.4577, 136.7233` (`,`の後にスペースあり)

コピーした座標は他のアプリで利用することを想定しています。

地点の右クリック - **Google マップ**
![context-menu_google-map](https://github.com/user-attachments/assets/adae657e-5c0c-4b29-8a6c-a8a5e1bca132)

地点の右クリック - **地理院地図Vector**
![context-menu_gsimap_vector](https://github.com/user-attachments/assets/0baac0fa-0e55-477e-a8fe-f0956a3b6240)

**Comment by johofukyu** [comment]
地理院地図Vectorをご利用いただきありがとうございます。
 いただいたご意見は今後の参考にさせていただきます。
以上、どうぞよろしくお願いいたします。

**Comment by nek7u** [comment]
Close #24
