### ISSUE TITLE
道路のftCode

### ISSUE THREAD

**Issue by wakufactory** [gsi-cyberjapan/gsimaps-vector-experiment#3]
「地物コード及び表示ズームレベル一覧」において道路のftCodeの下位2桁が01-04しかなくダブっていますが、11-14,21-24,31-34も実際のデータに存在するようです。表の間違いではないでしょうか。

**Comment by johofukyu** [comment]
ご指摘ありがとうございます。
標記、間違いを確認しましたので「地物コード及び表示ズームレベル一覧」を修正いたしました。
今後ともよろしくお願いします。

**Comment by wakufactory** [comment]
修正を確認したのでクローズします。
