### ISSUE TITLE
waterareaのダブリについて

### ISSUE THREAD

**Issue by wakufactory** [gsi-cyberjapan/gsimaps-vector-experiment#4]
不具合という訳ではないのですが、データを見ていて気になった点があります。
waterareaのデータが妙に大きいと思って見てみましたが、エリアがだいぶ重複してポリゴン化されてるようです。試しに半透明で塗ってみましたが、堀に比べ川の部分が濃くなっていて、重複して描画されていることがわかります。

<img width="386" alt="water" src="https://user-images.githubusercontent.com/1425598/62459431-4b802480-b7ba-11e9-8d86-5f9d276aa46d.png">

これはこういうものなのでしょうか。

**Comment by wakufactory** [comment]
同様の現象が建物でもあるようです。

<img width="184" alt="build" src="https://user-images.githubusercontent.com/1425598/62462084-702bca80-b7c1-11e9-9d5d-60c4cbf5612f.png">

この例では、右側がタイルの端で、タイルの端に掛かってる建物が濃くなっています。つまり、複数タイルにまたがる地物がダブって登録されている、ということのように見えます。

**Comment by johofukyu** [comment]
国土地理院の地理院地図担当です。

お問合せいただいた件に関しまして、
ご指摘の通り、建物の例のように2つのタイルにまたがる
ポリゴンは双方のタイルにデータが存在しております。
これは、タイル境界部での描画をシームレスに行うための処理です。

したがいまして、水部のように3つ以上のタイルにまたがるポリゴンに
つきましては、それらのタイルそれぞれにデータが存在している可能性があります。
このため水部において、重複した描画が行われている箇所が存在すると考えられます。

以上、よろしくお願いします。

**Comment by wakufactory** [comment]
すみません。説明不足でした。2つのタイルの双方に含まれるのは問題ないと思われますが、
上記の例では、1つ分のタイルデータしか描画していません。1つのタイルデータに同じポリゴンがダブって登録されており、これはデータ量的にも描画負荷的にも無駄と思われます。

**Comment by johofukyu** [comment]
本日（2020/3/19）の全国データ公開に伴い、ご指摘の件は解消しております。
どうぞよろしくお願いいたします。

**Comment by wakufactory** [comment]
ありがとうございます。クローズします。
