### ISSUE TITLE
地図内容について

### ISSUE THREAD

**Issue by wakufactory** [gsi-cyberjapan/gsimaps-vector-experiment#5]
zoom8-10で、利根川がriverではなくlakeのレイヤに入っています。これは意図したものでしょうか？

個別の地図の内容についてここでissueを挙げるのは適切ではないように思いますが、他に報告すべき場所があれば教えていただきたく思います。

**Comment by johofukyu** [comment]
国土地理院の地理院地図担当です。

現状、zoom8-10において、ポリゴンで湖池と接続している河川については、
技術的な問題から湖池のレイヤに含まれている状態となっています。

今後改善に向けて検討を行う予定です。
以上、よろしくお願いします。

**Comment by wakufactory** [comment]
了解しました。一旦クローズします。
