### ISSUE TITLE
路線コード駅コードについて

### ISSUE THREAD

**Issue by wakufactory** [gsi-cyberjapan/gsimaps-vector-experiment#6]
railwayレイヤの路線と駅のコードrtCode,staCodeについて、具体的なコードと駅名の対応表はどこにありますでしょうか。

**Comment by johofukyu** [comment]
国土地理院の地理院地図担当です。

rtCode及びstaCodeの属性値については、描画のため管理主体の判別等に用いているもので、
お問い合わせのような個別の駅名との対応表については保有しておりません。

■（参考）地理院地図Vector（仮称）属性解説書、9ページ
https://maps.gsi.go.jp/help/pdf/vector/attribute.pdf

以上、よろしくお願いします。

**Comment by wakufactory** [comment]
了解しました。
これは要望になりますが、現状注記情報と駅のベクトルデータとの対応づけが無いために、ベクトルデータとしてどこの駅なのかの情報を取得することができません。staCodeに具体的な駅コードを振るか、注記情報との対応づけがあると利便性が増すと思います。

**Comment by johofukyu** [comment]
ご意見をいただきありがとうございます。
今後の改良の際の参考とさせていただきます。

**Comment by wakufactory** [comment]
よろしくお願いします。一旦クローズします。
