### ISSUE TITLE
地物の属性一覧ドキュメントの誤り

### ISSUE THREAD

**Issue by wakufactory** [gsi-cyberjapan/gsimaps-vector-experiment#7]
細かい点ですが、
地物の属性一覧の鉄道の項目、sngDblはsnglDblの誤りと思われます。

**Comment by johofukyu** [comment]
国土地理院の地理院地図担当です。

ご指摘いただきました件につきまして、ご不便をおかけしました。
項目名の誤りを訂正したドキュメントを掲載しておりますのでご確認ください。

よろしくお願いいたします。

**Comment by wakufactory** [comment]
ありがとうございます。クローズします。
