### ISSUE TITLE
縦書きテキストのためのスタイル指定

### ISSUE THREAD

**Issue by frogcat** [gsi-cyberjapan/gsimaps-vector-experiment#8]
情報提供と質問です。
2019-08-29 にリリースされた mapbox-gl-js v1.3.0 で text-writing-mode というレイアウトプロパティが導入されました。vertical というキーワードを指定するとテキストを縦書きで表示することができるようです。

<https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-writing-mode>

現在の地理院地図 VECTOR は mapbox-gl-js v 0.52.0 を使用しており、縦書きには独自のプラグインで対応していると思うのですが、今後、例えば正式運用の際に  mapbox-gl-js v1.3.0 にバージョンアップしてスタイルも刷新される、といったことは予定したほうがよいのでしょうか？あるいは 0.52.0 を継続使用していくような方針でしょうか？

**Comment by johofukyu** [comment]
国土地理院の地理院地図担当です。

本件、情報提供いただきありがとうございます。

当院の方針としましては、現在のバージョンに拘ることはなく、
適宜、最善のバージョンを使用していきたいと考えています。

以上、よろしくお願いいたします。
