### ISSUE TITLE
道路のstring_valueが文字化け？

### ISSUE THREAD

**Issue by yosimusakun** [gsi-cyberjapan/gsimaps-vector-experiment#9]
地理院からダウンロードした任意のpbfをprotocol bufferで読み取ると，
レイヤ名が道路のstring_valueがところどころ文字化けしています．
具体的には，3m未?や市区町?道等など，一部分が0xEFBFBDになっています．
(0xEFBFBDはutf-8化に失敗している証拠)
もちろん，protocol bufferが原因ではなく，生のpbfをバイナリ解析すると該当部分が0xEFBFBDとなっていることからpbfに問題があるといえます．
確認および修正願えますでしょうか．
よろしくお願いいたします．

**Comment by johofukyu** [comment]
国土地理院の地理院地図担当です。

ご指摘いただきましてありがとうございます。
この文字化けについては、当方でも把握しており、
現在調査を行っているところです。

**Comment by yosimusakun** [comment]
迅速なご返答ありがとうございます．
承知しました．
スムーズな解決を願っております．

**Comment by johofukyu** [comment]
本日、当方で把握している限りで文字化けの問題が解決しましたので、
文字化け修正後のpbfファイルに差替えております。

よろしければ、ご確認いただけますと幸いです。

**Comment by wakufactory** [comment]
文字化け問題、別要因だと思いますがまだ残っています。

有名な難読地名ですが"畬"が化けています。
https://maps.gsi.go.jp/vector/#15/35.612297/139.334499/&ls=vstd&disp=1&d=l

これはJIS第4水準の外字扱い文字からunicodeへの変換がうまくいってないケースだと思います。

**Comment by johofukyu** [comment]
"畬"の文字化けにつきましては、ご指摘いただきました通り、
前回までとは別の要因によって生じております。

どの過程で文字化けが生じているかについてまでは特定できておりますので、
今後具体的な解決手段を調査して参ります。

**Comment by johofukyu** [comment]
本日（2020/3/19）の全国データ公開に伴い、ご指摘の件は解消しております。
どうぞよろしくお願いいたします。

**Comment by wakufactory** [comment]
"畬"の件は確認しました。クローズお願いします。
